// var whoopie = new Audio();
// whoopie.src = "sound/whoopie.mp3";
// var hereWeGo = new Audio();
// hereWeGo.src = "sound/here_we_go.mp3";
// var monkey = new Audio();
// monkey.src = "sound/monkey.mp3";
// monkey.loop = true;
// var laugh = new Audio();
// laugh.src = "sound/laugh.mp3";
